### ISSUE TITLE
Empty Table Row and rowspan crashes

### ISSUE THREAD

**Issue by lasbec** [Aymkdn/html-to-pdfmake#163]
The following HTML snipet will crash the call of htmlToPdfmake:

```
<div><table width="225"><tbody><tr><td width="225" rowspan="2">A Cell</td></tr><tr></tr></tbody></table></div>
```

The error says
```
Cannot read property 'splice' of undefined
TypeError: Cannot read property 'splice' of undefined
    at htmlToPdfMake.setRowSpan (/home/lasse/idadwh/node_modules/html-to-pdfmake/index.js:524:15)
    at /home/lasse/idadwh/node_modules/html-to-pdfmake/index.js:243:33
    at Array.forEach (<anonymous>)
    at /home/lasse/idadwh/node_modules/html-to-pdfmake/index.js:226:29
    at Array.forEach (<anonymous>)
    at /home/lasse/idadwh/node_modules/html-to-pdfmake/index.js:220:24
    at Array.forEach (<anonymous>)
    at htmlToPdfMake.parseElement (/home/lasse/idadwh/node_modules/html-to-pdfmake/index.js:214:23)
    at /home/lasse/idadwh/node_modules/html-to-pdfmake/index.js:183:29
    at Proxy.forEach (<anonymous>)
```

After removing the empty table row and the rowspan="2" it works just fine.

The sipet was created by copy-pasting excel cells into a tinymce editor.

**Comment by Aymkdn** [comment]
Yes, you need to provide a valid and simple HTML code. An empty `<tr></tr>` with a `rowspan=2` makes no sense…

Sorry, but it won't be fixed.
